Update detector.go
gogits/chardet pull request #7
Opened 2021-08-11 07:59 UTC by moredure

2021-08-11 13:52 UTC, moredure commented
Should perform better and less memory allocations

2021-11-11 15:08 UTC, unknwon commented
Thanks for the PR!

Can you give more background about why this is going to faster and provide some benchmarks?

2021-11-12 08:39 UTC, moredure commented
hi @unknwon , the only change here is that we don't allocate slice for holding and sorting detected values in order to get the optimal, we just reading values until find optimal

2021-11-12 12:26 UTC, unknwon commented
This PR also adds code to spawn goroutines which I'm not convinced this is a good idea within this function :)

2021-11-14 19:04 UTC, moredure commented
DetectBest is based on DetectAll which is spawning goroutines which was copied

2021-11-14 19:07 UTC, moredure commented
If you are interested in removing goroutine creation for this and other APIs i think it's better to do it in separate pull requests with breaking changes to internals for matchHelper to getting rid of channels and goroutines

2021-11-15 11:08 UTC, unknwon commented
Gotcha, thanks for the context!

If we want to make progress for this PR, I need to understand:

1. how less memory allocation claimed make actual performance improvements, and what's the proof of this conclusion?
2. What's stopping us from changing `DetectAll` directly?

2021-11-15 13:42 UTC, moredure commented
DetectAll returns all possible encodings fits data slice sorted by confidence, while DetectBest returns single one with best/higher possible confidence across all detected. in case of DetectBest we don't need any conversion. I will share benchmarks soon.

2021-11-15 14:08 UTC, moredure commented
```
goos: darwin
goarch: amd64
pkg: github.com/gogs/chardet
cpu: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
BenchmarkDetectBest
BenchmarkDetectBest/old
BenchmarkDetectBest/old-4         	    4834	    335575 ns/op	   15444 B/op	      48 allocs/op
BenchmarkDetectBest/new
BenchmarkDetectBest/new-4         	    5865	    199170 ns/op	   13428 B/op	      46 allocs/op
PASS

Process finished with the exit code 0
```

2021-11-15 16:24 UTC, moredure commented
Non concurrent detectBest make only 5 allocation but has worser ns/op

2021-11-16 17:33 UTC, moredure commented
removing byteStats and converting it into bytearray also cuts one more allocation

2021-11-18 02:53 UTC, unknwon requested changes
Thanks for the follow up, I think we can merge this PR after some clean up.

2021-11-18 02:53 UTC, unknwon commented on recognizer.go
> +
```suggestion
```

2021-11-18 02:53 UTC, unknwon commented on detector_test.go
> +}
This file does not look like had been ran over by "gofmt", could you do that?

2021-11-18 02:53 UTC, unknwon commented on detector_test.go
> +	b.Run("new", func(b *testing.B) {
Thanks for the benchmark comparison! To commit the PR, please clean up/remove old implementation here and only leave the benchmark code for the latest implementation.

2021-11-20 15:40 UTC, unknwon approved these changes
Thanks for the follow up!

2021-11-20 15:40 UTC, merged